name: Generate JSON


on:
  push:
    branches: [ master ]
    tags: [ ]
    patterns: [ "**[ci]**" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        run: node script.js
      - name: Copy and rename file
        run: cp output.json docs/avg.json
      - name: Create commit
        env:
          GIT_TOKEN: ${{ secrets.GIRINDEX_WORKFLOW_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add docs/avg.json
          git commit -m "Add generated JSON output"
          git push https://x-access-token:$GIT_TOKEN@github.com/$GITHUB_REPOSITORY.git HEAD:$GITHUB_REF
